### ISSUE TITLE
mystyle.css has wrong URL for molecule image

### ISSUE THREAD

**Issue by rwalkerands** [SISS/sissvoc#2]
`resources/default/css/mystyle.css` refers to `../images/molecule.jpg`, but there's no such file in the built WAR file. The reference should be to `../images/molecule.png` instead.

See also the issue I filed against elda for standalone-banner.png: https://github.com/epimorphics/elda/issues/133

**Comment by jyucsiro** [comment]
Modified the css to point to the actual file now. Will need to republish the war file.
