### ISSUE TITLE
Some queries can return duplicates

### ISSUE THREAD

**Issue by rwalkerands** [SISS/sissvoc#5]
I filed this issue against the Elda library:

https://github.com/epimorphics/elda/issues/173

But because of LDA spec ambiguity, it's probably not a defect in Elda, but a case where endpoint queries have to be specified a bit more explicitly.

In short: some of the queries in the "off-the-shelf" SISSVoc spec template can return duplicate results. This happens if the SPARQL query can match in multiple ways. The case in point is the `/concept?labelcontains={text}` endpoint, and you do a search where there's a hit against _both_ a concept's prefLabel and its altLabel.

You'll see in the Elda GitHub issue that I've added a workaround.

The same issue will (probably) apply to all ListEndpoints that are currently implemented using api:where, and which contain a UNION.

**Comment by jyucsiro** [comment]
Thanks. The workaround looks interesting.

**Comment by rwalkerands** [comment]
Any thoughts on whether you would/will change the template?

**Comment by jyucsiro** [comment]
Hi Richard,

Yes, we'd be willing to change the template to fix the duplicate results. Is the proposal to switch from using api:where to api:select using a full SPARQL select query with DISTINCT clause?

**Comment by rwalkerands** [comment]
Well, it's _a_ proposal.

There seem to be two ways:

1. Change api:where to api:select, as I did in the example at https://github.com/epimorphics/elda/issues/173#issuecomment-262409344
2. Force sorting of the results, as per one of the ways given in the section "Ordering" at https://github.com/UKGovLD/linked-data-api/blob/wiki/API_Selecting_Resources.md

For example, compare the results of:

* http://vocabs.ands.org.au/repository/api/lda/aodn/aodn-instrument-vocabulary/version-1-0/concept?labelcontains=SMP-ODO
* http://vocabs.ands.org.au/repository/api/lda/aodn/aodn-instrument-vocabulary/version-1-0/concept?labelcontains=SMP-ODO&_sort=prefLabel

(You wouldn't do it this way (adding the parameter to the URL), but use api:orderBy or api:sort in the template.)

I think I prefer option 1 (use api:select).

**Comment by rwalkerands** [comment]
Anything going to happen here?

**Comment by jyucsiro** [comment]
Looking into this a bit now that elda is up to date. See PR #9 for some changes.

**Comment by jyucsiro** [comment]
Rolled into release v3.6-rc-3.
