### ISSUE TITLE
Upgrade SISSVoc to latest version of ELDA 

### ISSUE THREAD

**Issue by jyucsiro** [SISS/sissvoc#8]
SISSVoc provides a .war file as a packaged ELDA distro. Elda is now at version 2.0.0. This ticket is for upgrading the distro to the latest version of ELDA.

**Comment by jyucsiro** [comment]
Link to ELDA http://repository.epimorphics.com/com/epimorphics/lda/elda-standalone/2.0.0/elda-standalone-2.0.0-exec-war.jar

**Comment by dr-shorthair** [comment]
Probably need to keep @rwalkerands richard.walker@ardc.edu.au in the loop here

**Comment by rwalkerands** [comment]
Already in the loop (I subscribe to everything here). Feel free to proceed ...

**Comment by jyucsiro** [comment]
No worries. I don't think the config files in this repo need to change, but the distro available on http://www.sissvoc.info/ will need to be updated. A suggested place for the .war binary would be as part of the GH release, rather than a separate server

**Comment by jyucsiro** [comment]
Hi @dr-shorthair @rwalkerands - some update on this. I've generated a dist .war file for v3.6-RC1 of sissvoc. See https://github.com/SISS/SISSVoc/releases/tag/sissvoc-3.6-rc-1 

This should work if you drop it into Apache Tomcat/Jetty etc. or docker-compose if you so choose (see docker-compose.yml).

A default sissvoc deployment is included and can be viewed once deployed, e.g. http://localhost:8080/sissvoc/default/concept (which uses the demo SISSVoc Pizza skos dataset).
